[package]
name = "llm_inference"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
tokenizers = "0.22.1"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.47.1"

mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git", branch = "master", features = ["cuda"] }

